app/locale/de.json
app/locale/fr.json
app/locale/ja.json

Japanese locale! 
and i found some typo on other locale file :P

add ja.json & fix typo

---

app/js/actions.js

This should also fix my translation issue for piece by piece

Fix the full name of "Piece by Piece"

---

app/locale/fr.json

Fix spelling of Ingenuity in French. Closes #101.

Fix issue #101 : Ingenuity in french is "Ingéniosity" not "Inqéniosity"

---

app/data/recipedb/Alchemist.json
app/data/recipedb/Armorer.json
app/data/recipedb/Blacksmith.json
app/data/recipedb/Carpenter.json
app/data/recipedb/Culinarian.json
app/data/recipedb/Goldsmith.json
app/data/recipedb/Leatherworker.json
app/data/recipedb/Weaver.json
app/js/services/locale.js
app/locale/cn.json

I modified db files to add Chinese names to them.
Please make changes to your db generator so the cn field would be keeped while regenerating data.
But I also keep a tool in my fork that can refill cn data when it's missing, but better keep them to avoid more PRs.

Add Chinese Localizations

---

app/js/ffxivcraftmodel.js
app/locale/de.json
app/locale/fr.json
app/locale/ja.json

Has the translations for the new Stormblood actions, fixes #144.
Also has another commit with fix to small bug with Comfort Zone, where it wasn't giving its CP restore if you went down to exactly 0 CP.

New action translations (and small bugfix)

---

app/js/controllers/main.js
app/views/simulator.html

A small feature to add buttons to import/export the current sequence to a JSON string, that can be easily shared among users.

Feature to import/export current crafting sequence to a string

---

app/data/recipedb/Alchemist.json
app/data/recipedb/Armorer.json
app/data/recipedb/Blacksmith.json
app/data/recipedb/Carpenter.json
app/data/recipedb/Culinarian.json
app/data/recipedb/Goldsmith.json
app/data/recipedb/Leatherworker.json
app/data/recipedb/Weaver.json
app/js/ffxivcraftmodel.js

Added new recipes, and some adjustments to crafting formula.
The formula for 70** synths isn't quite right still, collecting data to adjust it.

4.0.5 update

---

app/js/controllers/main.js
app/js/ffxivcraftmodel.js
app/js/services/actions.js

Update for 4.2, along with general update for crafting equations.
Also has a few various bug fixes.

4.2 update

---

app/js/ffxivcraftmodel.js

More updates to crafting formula.
Main thing I am not sure on and need more data is Ingenuity (I & II) for crafters level 51-64.

Formula updates

---

app/css/app.css
app/index.html
app/js/controllers/macroimport.js
app/js/controllers/main.js
app/modals/macroimport.html
app/views/simulator.html

Replace prompt with modal for macro import feature.

---

app/js/components/macros.js
app/js/controllers/main.js
app/locale/cn.json
app/locale/de.json
app/locale/en.json
app/locale/fr.json
app/locale/ja.json
app/locale/ko.json
app/modals/options.html

Hello, i'm refering to this issue, to offer the capacity to enable or disable sound effects from options settings #83
Hope this can help you :)

Issue#83 - Option for disabling sounds effect

---

app/js/actions.js

Fix for Issue number #277 
- Reduce CP cost 10 -> 0

#277 - Name of the elements durability

---

app/data/buffs/Food.json
app/data/buffs/Medicine.json

This adds the new Food and Medicine for crafting.
Only with en, fr, ja, de translation, ko and cn are currently using the english names!
#289

Add shb Food / Medicine

---

app/js/ffxivcraftmodel.js

Cater for rapid synth III below 20 durability.

Rapid Synth III conditional

---

app/js/ffxivcraftmodel.js

It also does not affect the Skill but instead directly affects the
resulting values

Innovation increases both quality and progress

---

app/js/ffxivcraftmodel.js

Reflect was stacking up too many initial inner quiets

---

app/js/actions.js

Basic Synthesis has 100 % success rate

---

app/js/ffxivcraftmodel.js

This fixes various issues in the model such as #361 and #358.

Model fixes

---

app/locale/cn.json

update cn locale

---

app/js/ffxivcraftmodel.js

Innovation was changed to no longer affect progress, but have a larger effect
on quality.

Adjust Innovation skill for 5.2
